sudo: required

services:
  - docker

before_install:
  - docker info
  - docker build -t hrektts/gitlab-ci-multi-runner-c-cpp .

script:
  - docker run -it hrektts/gitlab-ci-multi-runner-c-cpp gcc -v
  - docker run -it hrektts/gitlab-ci-multi-runner-c-cpp g++ -v
